const ResponseConst = {
    CODE: {
        CODE_SUCCESS: 1,
        CODE_FAILURE: -1,
        CODE_INVALID_PARAM: -2,
        CODE_INVALID_RANGE: -3,
        CODE_COULD_NOT_PARSE: -4,
        CODE_ALREADY_EXIST: -5,
        CODE_INVALID_LOCALE: -6,
        CODE_UNAUTHORIZED: -7,
        CODE_BLOCKED: -8,
        CODE_NO_PROPER_VALUE: -9,
        CODE_NO_PROPER_FORM: -10,
        CODE_NOT_EXISTING: -11,
    },
    MSG: {
        MSG_SUCCESS: 'Request Processed Successfully.',
        MSG_INVALID_RANGE: 'Invalid Range of value.',
        MSG_INVALID_PARAM: 'You just have sent invalid parameter! Please Check if there is any problem with specs.',
        MSG_FAILURE: 'Something went wrong',
        MSG_PARSE_ERROR: 'server.Server has failed to parse json data.',
        MSG_ALREADY_EXIST: 'Already Exist!',
        MSG_SAVE_SUCCESS: 'Saving succeeded.',
        MSG_SAVE_FAIL: 'Saving failed.',
        MSG_ILLEGAL_STATE: 'Something goes crazy',
        MSG_NONE: 'Process succeeded but unknown error occurred.',
        MSG_INVALID_LOCALE: 'The locale string you were about to apply is not applicable for setting.',
        MSG_UNAUTHORIZED: 'The access token you sent is not qualified to access.',
        MSG_BLOCKED: 'The host you are using is blocked from server',
        MSG_NO_PROPER_VALUE: 'The value you used is not proper value for process',
        MSG_NO_PROPER_FORM: 'The file you used is not proper form for process.',
        MSG_NOT_EXISTING: 'There is no tuple satisfying these conditions.',
    },
    CUSTOM: {
        MSG_INVALID_EMAIL: 'You entered wrong email form',
        MSG_INVALID_EMAIL_ORG: 'You must enter university email',
    },
}

export default ResponseConst
